# Generated by Django 5.2 on 2025-04-14 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_transaccion_usuario_alter_transaccion_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.categoria'),
        ),
    ]
