# Generated by Django 5.2 on 2025-05-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='transacciones/'),
        ),
    ]
